#! /bin/sh

	./amaze "amaze_levels/001.xml"
	./amaze "amaze_levels/002.xml"
	./amaze "amaze_levels/003.xml"
	./amaze "amaze_levels/004.xml"
	./amaze "amaze_levels/005.xml"
	./amaze "amaze_levels/006.xml"
	./amaze "amaze_levels/007.xml"
	./amaze "amaze_levels/008.xml"
	./amaze "amaze_levels/009.xml"
	./amaze "amaze_levels/010.xml"
	./amaze "amaze_levels/011.xml"
	./amaze "amaze_levels/012.xml"
	./amaze "amaze_levels/013.xml"
	./amaze "amaze_levels/014.xml"
	./amaze "amaze_levels/015.xml"
	./amaze "amaze_levels/016.xml"
	./amaze "amaze_levels/017.xml"
	./amaze "amaze_levels/018.xml"
	./amaze "amaze_levels/019.xml"
	./amaze "amaze_levels/020.xml"
	./amaze "amaze_levels/021.xml"
	./amaze "amaze_levels/022.xml"
	./amaze "amaze_levels/023.xml"
	./amaze "amaze_levels/024.xml"
	./amaze "amaze_levels/025.xml"
	./amaze "amaze_levels/026.xml"
	./amaze "amaze_levels/027.xml"
	./amaze "amaze_levels/028.xml"
	./amaze "amaze_levels/029.xml"
	./amaze "amaze_levels/030.xml"
	./amaze "amaze_levels/031.xml"
	./amaze "amaze_levels/032.xml"
	./amaze "amaze_levels/033.xml"
	./amaze "amaze_levels/034.xml"
	./amaze "amaze_levels/035.xml"
	./amaze "amaze_levels/036.xml"
	./amaze "amaze_levels/037.xml"
	./amaze "amaze_levels/038.xml"
	./amaze "amaze_levels/039.xml"
	./amaze "amaze_levels/040.xml"
	./amaze "amaze_levels/041.xml"
	./amaze "amaze_levels/042.xml"
	./amaze "amaze_levels/043.xml"
	./amaze "amaze_levels/044.xml"
	./amaze "amaze_levels/045.xml"
	./amaze "amaze_levels/046.xml"
	./amaze "amaze_levels/047.xml"
	./amaze "amaze_levels/048.xml"
	./amaze "amaze_levels/049.xml"
	./amaze "amaze_levels/050.xml"
	./amaze "amaze_levels/052.xml"
	./amaze "amaze_levels/053.xml"
	./amaze "amaze_levels/059.xml"
	./amaze "amaze_levels/060.xml"
	./amaze "amaze_levels/061.xml"
	./amaze "amaze_levels/063.xml"
	./amaze "amaze_levels/065 dan.xml"
	./amaze "amaze_levels/066 dan.xml"
	./amaze "amaze_levels/067 dan.xml"
	./amaze "amaze_levels/068 dan.xml"
	./amaze "amaze_levels/069 dan.xml"
	./amaze "amaze_levels/070 dan.xml"
	./amaze "amaze_levels/071 dan.xml"
	./amaze "amaze_levels/072 dan.xml"
	./amaze "amaze_levels/073 dan.xml"
	./amaze "amaze_levels/074 dan.xml"
	./amaze "amaze_levels/075 dan.xml"
	./amaze "amaze_levels/076 dan.xml"
	./amaze "amaze_levels/077 dan.xml"
	./amaze "amaze_levels/078 dan.xml"
	./amaze "amaze_levels/079 dan.xml"
	./amaze "amaze_levels/080 dan.xml"
	./amaze "amaze_levels/081 dan.xml"
	./amaze "amaze_levels/082 dan.xml"
	./amaze "amaze_levels/083 dan.xml"
	./amaze "amaze_levels/084 dan.xml"
	./amaze "amaze_levels/085 dan.xml"
	./amaze "amaze_levels/086 dan.xml"
	./amaze "amaze_levels/087 dan.xml"
	./amaze "amaze_levels/088 dan.xml"
	./amaze "amaze_levels/094 dan.xml"
	./amaze "amaze_levels/095 dan.xml"
	./amaze "amaze_levels/096 dan.xml"
	./amaze "amaze_levels/097 dan.xml"
	./amaze "amaze_levels/098 dan.xml"
	./amaze "amaze_levels/102.xml"
	./amaze "amaze_levels/105.xml"
	./amaze "amaze_levels/106.xml"
	./amaze "amaze_levels/107 dan.xml"
	./amaze "amaze_levels/109 dan.xml"
	./amaze "amaze_levels/110 dan.xml"
	./amaze "amaze_levels/112 dan.xml"
	./amaze "amaze_levels/113 dan.xml"
	./amaze "amaze_levels/114 dan.xml"
	./amaze "amaze_levels/115 dan.xml"
	./amaze "amaze_levels/116 dan.xml"
	./amaze "amaze_levels/117 dan.xml"
	./amaze "amaze_levels/118 dan.xml"
	./amaze "amaze_levels/119 dan.xml"
	./amaze "amaze_levels/120 dan.xml"
	./amaze "amaze_levels/122 dan.xml"
	./amaze "amaze_levels/123 dan.xml"
	./amaze "amaze_levels/130 dan.xml"
	./amaze "amaze_levels/131 dan.xml"
	./amaze "amaze_levels/132 dan.xml"
	./amaze "amaze_levels/133 dan.xml"
	./amaze "amaze_levels/134 dan.xml"
	./amaze "amaze_levels/135.xml"
	./amaze "amaze_levels/136.xml"
	./amaze "amaze_levels/137.xml"
	./amaze "amaze_levels/138.xml"
	./amaze "amaze_levels/139.xml"
	./amaze "amaze_levels/140.xml"
	./amaze "amaze_levels/142.xml"
	./amaze "amaze_levels/145 dan.xml"
	./amaze "amaze_levels/147 dan.xml"
	./amaze "amaze_levels/151 dan.xml"
	./amaze "amaze_levels/152 dan.xml"
	./amaze "amaze_levels/154 dan.xml"
	./amaze "amaze_levels/156 dan.xml"
	./amaze "amaze_levels/158 dan.xml"
	./amaze "amaze_levels/160 dan.xml"
	./amaze "amaze_levels/161 dan.xml"
	./amaze "amaze_levels/162 dan.xml"
	./amaze "amaze_levels/163 dan.xml"
	./amaze "amaze_levels/164 dan.xml"
	./amaze "amaze_levels/165 dan.xml"
	./amaze "amaze_levels/166 dan.xml"
	./amaze "amaze_levels/168 dan.xml"
	./amaze "amaze_levels/169 dan.xml"
